### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by SilentEngineer1999** [robmikh/WinUI3Win2DSwapChain#2]
I am able to record audio from Mic with windows api and System audio with Naudio and saving it in .Wav file. Im using FFmpeg to later merge the audio and video recording. Is there any way to write the audio to the video file directly without saving it seperately and is there any way to do the merging of audio and video file without FFmpeg ?

**Comment by SilentEngineer1999** [comment]
`// Open the video file
StorageFile videoFile = await StorageFile.GetFileFromPathAsync("C:\\path\\to\\video.mp4");
MediaClip videoClip = await MediaClip.CreateFromFileAsync(videoFile);

// Open the audio file
StorageFile audioFile = await StorageFile.GetFileFromPathAsync("C:\\path\\to\\audio.mp3");
BackgroundAudioTrack audioTrack = await BackgroundAudioTrack.CreateFromFileAsync(audioFile);

// Create a new MediaComposition object and add the video clip and audio track
MediaComposition composition = new MediaComposition();
composition.Clips.Add(videoClip);
composition.BackgroundAudioTracks.Add(audioTrack);

// Render the composition to a new video file
StorageFile outputFile = await ApplicationData.Current.LocalFolder.CreateFileAsync("output.mp4", CreationCollisionOption.GenerateUniqueName);
MediaEncodingProfile profile = MediaEncodingProfile.CreateMp4(VideoEncodingQuality.HD720p);
await composition.RenderToFileAsync(outputFile, MediaTrimmingPreference.Fast, profile); `


this code takes a lot of time to merge the video and audio and is not as good clarity as ffmpeg video

**Comment by robmikh** [comment]
You'll need to add an audio stream to your MediaStreamSource, as well as configure the transcoder to also transcode audio. I'd take a look at the MediaStreamSource documentation. But this is an area I can't give much guidance on, I haven't tried it myself.
