### ISSUE TITLE
Video Editing

### ISSUE THREAD

**Issue by SilentEngineer1999** [robmikh/WinUI3Win2DSwapChain#3]
I have created a video trimming function that works. Is there a way to cut the video like the cut part of the video doesn't appear in the video. if it is a 20 mins video I cut min 10 - 15 the video gets shortened by 5 mins and it skips by 5 mins. Do you know how to do this with windows.media.editing.

**Comment by robmikh** [comment]
Sorry, I'm not familiar with those APIs. I can answer questions about  Windows.Graphics.Capture or Windows.UI.Composition.
