### ISSUE TITLE
How to write the frames to a video file?

### ISSUE THREAD

**Issue by silentEngineer009** [robmikh/WinUI3Win2DSwapChain#4]
So i am taking the frames from a video file and i want to write it to another video file 
`        private async void TrimClip_Click(object sender, RoutedEventArgs e)
        {
            var picker = new Windows.Storage.Pickers.FileOpenPicker();
            picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.VideosLibrary;
            picker.FileTypeFilter.Add(".mp4");
            var windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(this);
            InitializeWithWindow.Initialize(picker, windowHandle);
            StorageFile pickedFile = await picker.PickSingleFileAsync();

            for (int i = 0; i < 1000;  i+=16) 
            {
                ExtractFrames(i, pickedFile);
                await Task.Delay(1000);
            }
            
        }

        public async void ExtractFrames(int x, StorageFile pickedFile)
        {
            TimeSpan timeOfFrame = new TimeSpan(0, 0, 0,0,x);

            //pick mp4 file

            //Get video resolution
            List<string> encodingPropertiesToRetrieve = new List<string>
            {
                "System.Video.FrameHeight",
                "System.Video.FrameWidth"
            };
            IDictionary<string, object> encodingProperties = await pickedFile.Properties.RetrievePropertiesAsync(encodingPropertiesToRetrieve);
            uint frameHeight = (uint)encodingProperties["System.Video.FrameHeight"];
            uint frameWidth = (uint)encodingProperties["System.Video.FrameWidth"];
            ///

            //Use Windows.Media.Editing to get ImageStream
            var clip = await MediaClip.CreateFromFileAsync(pickedFile);
            var composition = new MediaComposition();
            composition.Clips.Add(clip);

            var imageStream = await composition.GetThumbnailAsync(timeOfFrame, (int)frameWidth, (int)frameHeight, VideoFramePrecision.NearestFrame);
            ///

            //generate bitmap 
            var writableBitmap = new WriteableBitmap((int)frameWidth, (int)frameHeight);
            writableBitmap.SetSource(imageStream);

            //generate some random name for file in PicturesLibrary
            var saveAsTarget = await KnownFolders.PicturesLibrary.CreateFileAsync("IMG" + Guid.NewGuid().ToString().Substring(0, 4) + ".jpg");

            //get stream from bitmap
            Stream stream = writableBitmap.PixelBuffer.AsStream();
            byte[] pixels = new byte[(uint)stream.Length];
            await stream.ReadAsync(pixels, 0, pixels.Length);

            using (var writeStream = await saveAsTarget.OpenAsync(FileAccessMode.ReadWrite))
            {
                var encoder = await BitmapEncoder.CreateAsync(BitmapEncoder.JpegEncoderId, writeStream);
                encoder.SetPixelData(
                    BitmapPixelFormat.Bgra8,
                    BitmapAlphaMode.Premultiplied,
                    (uint)writableBitmap.PixelWidth,
                    (uint)writableBitmap.PixelHeight,
                    96,
                    96,
                    pixels);
                await encoder.FlushAsync();

                using (var outputStream = writeStream.GetOutputStreamAt(0))
                {
                    await outputStream.FlushAsync();
                }
            }

        }` how to write the frames to a video file instead of a jpeg

**Comment by robmikh** [comment]
The same way you would make a video from buffers returned by the capture API. Use the Windows.Media.Transcoding APIs as shown in the SimpleRecorder repo.
